export const PartnersData = [
  {
    id: 0,
    title: "Unicef For Every Child",
    description:
      "Built the child helpline Case Management and Call Center for Childline Kenya. The work done was, Requirement,Gathering, wireframing, SoftwareDevelopment, Deployment, user testing, Training, and User Support.Project Timelines was 8 Months",
    logo: './assets/display_photos/logo-placeholder.png',
    Link: "https://www.unicef.org/child-alert/severe-wasting",
    contactEmail: "info@bitz-itc.com",
    contactPhone: "+254 700 000 000",
  },
  {
    id: 1,
    title: "UNFPA",
    description:
      "Built the child helpline Case Management and Call Center for Childline Kenya. The work done was, Requirement,Gathering, wireframing, SoftwareDevelopment, Deployment, user testing, Training, and User Support.Project Timelines was 8 Months",
    logo: './assets/display_photos/logo-placeholder.png',
    Link: "https://www.unfpa.org/",
    contactEmail: "info@bitz-itc.com",
    contactPhone: "+254 713860954",
  },
  {
    id: 2,
    title: "Ministry of Community Development, Gender, Elderly and Children (MCDGEC-Tanzania)",
    description: "Partnership in developing comprehensive child protection systems across Tanzania.",
    logo: './assets/display_photos/logo-placeholder.png',
    Link: "https://www.turkanabasin.org/",
    contactEmail: "info@bitz-itc.com",
    contactPhone: "+254 713860954",
  },
  {
    id: 3,
    title: "Sauti 116 Helpline",
    description: "Collaborative efforts in establishing and maintaining child helpline services in Uganda.",
    logo: './assets/display_photos/logo-placeholder.png',
    Link: "https://sauti.mglsd.go.ug/sauti/",
    contactEmail: "info@bitz-itc.com",
    contactPhone: "+256 700 000 000",
  },
  {
    id: 4,
    title: "Ministry of Gender and Social Development",
    description: "Strategic partnership in implementing gender-focused technology solutions.",
    logo: './assets/display_photos/logo-placeholder.png',
    Link: "https://towersacco.co.ke/",
    contactEmail: "info@bitz-itc.com",
    contactPhone: "+256 700 000 000",
  },
  {
    id: 7,
    title: "Childline Kenya",
    description: "Direct partnership in providing comprehensive child protection services and technology solutions.",
    logo: './assets/display_photos/logo-placeholder.png',
    Link: "https://childlinekenya.co.ke/",
  },
]
