export const achievementsData = [
  {
    id: 1,
    title: "15+ Years of Excellence",
    description: "Over a decade and a half of delivering innovative technology solutions across East Africa",
    icon: "🏆",
    value: "15+",
    label: "Years",
  },
  {
    id: 2,
    title: "100+ Projects Delivered",
    description: "Successfully completed over 100 projects for government agencies and international organizations",
    icon: "📊",
    value: "100+",
    label: "Projects",
  },
  {
    id: 3,
    title: "4 Countries Served",
    description: "Strong presence across Kenya, Uganda, Tanzania, and Lesotho",
    icon: "🌍",
    value: "4",
    label: "Countries",
  },
  {
    id: 4,
    title: "99% Client Satisfaction",
    description: "Maintaining exceptional client satisfaction rates through quality delivery and support",
    icon: "⭐",
    value: "99%",
    label: "Satisfaction",
  },
  {
    id: 5,
    title: "24/7 Support",
    description: "Round-the-clock technical support and maintenance for all our solutions",
    icon: "🔧",
    value: "24/7",
    label: "Support",
  },
  {
    id: 6,
    title: "50+ Team Members",
    description: "Growing team of skilled professionals across different technology domains",
    icon: "👥",
    value: "50+",
    label: "Team Members",
  },
]
